# Dockerfile
FROM python:3.13-slim

# Variables d’environnement
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Travailler dans /app
WORKDIR /app

# Copier les fichiers de dépendances
COPY requirements.txt /app/

# Installer les dépendances
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copier tout le projet
COPY . /app/

# Exposer le port Django
EXPOSE 8000

# Commande par défaut (mode dev) — en production vous voudrez probablement utiliser gunicorn
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
