# Generated by Django 5.2.7 on 2025-10-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("idfournisseur", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("contact", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("idproduit", models.AutoField(primary_key=True, serialize=False)),
                ("nomproduit", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                ("seuilmin", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("idcommande", models.AutoField(primary_key=True, serialize=False)),
                ("quantite", models.IntegerField()),
                ("datelivraison", models.DateField()),
                (
                    "founisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="gestionstock.fournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="gestionstock.produit",
                    ),
                ),
            ],
        ),
    ]
