# Generated by Django 5.2.4 on 2025-10-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("idcategorie", models.AutoField(primary_key=True, serialize=False)),
                ("nomcat", models.CharField(max_length=100)),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("alimentaire", "Produits alimentaires"),
                            ("NA", "Non-alimentaires"),
                            ("PMA", "Produits à marque propre"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("idfournisseur", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_fournisseur",
                    models.CharField(
                        choices=[
                            ("local", "Producteur local"),
                            ("national", "Marque nationale"),
                            ("international", "Marque internationale"),
                            ("grossiste", "Grossiste / Centrale d’achat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("contact", models.IntegerField()),
                ("adresse", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("idcommande", models.AutoField(primary_key=True, serialize=False)),
                ("datelivraison", models.DateField()),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="gestionstock.fournisseur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("idproduit", models.AutoField(primary_key=True, serialize=False)),
                ("nomproduit", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                ("seuilmin", models.IntegerField()),
                ("prix", models.IntegerField()),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="gestionstock.categorie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="gestionstock.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionstock.produit",
                    ),
                ),
            ],
        ),
    ]
