# Generated by Django 5.2.7 on 2025-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionstock", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="founisseur",
            new_name="fournisseur",
        ),
    ]
