# Generated by Django 5.2.4 on 2025-10-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionstock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="quantite",
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="contact",
            field=models.IntegerField(),
        ),
    ]
