# Generated by Django 5.2.4 on 2025-10-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionstock",
            "0002_remove_commande_produit_remove_commande_quantite_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="prix",
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
