# Generated by Django 5.2.4 on 2025-10-20 14:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestionstock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caisse",
            fields=[
                (
                    "numero_caisse",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OUVERTE", "Ouverte"),
                            ("FERMEE", "Fermée"),
                            ("MAINTENANCE", "En maintenance"),
                        ],
                        default="FERMEE",
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SessionCaisse",
            fields=[
                ("idcaisse", models.IntegerField(primary_key=True, serialize=False)),
                ("date_ouverture", models.DateTimeField(auto_now_add=True)),
                ("date_fermeture", models.DateTimeField(blank=True, null=True)),
                (
                    "fond_caisse_initial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fond_caisse_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "montant_ventes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("nombre_transactions", models.IntegerField(default=0)),
                (
                    "ecart_caisse",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("OUVERTE", "Ouverte"), ("FERMEE", "Fermée")],
                        default="OUVERTE",
                        max_length=20,
                    ),
                ),
                ("commentaires", models.TextField(blank=True)),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="gestioncaisse.caisse",
                    ),
                ),
                (
                    "caissier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions_caisse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                ("idvente", models.IntegerField(primary_key=True, serialize=False)),
                ("numero_ticket", models.CharField(max_length=50, unique=True)),
                ("montant_brut", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "montant_remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("montant_tva", models.DecimalField(decimal_places=2, max_digits=10)),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("CARTE", "Carte bancaire"),
                            ("MOBILE", "Mobile Money"),
                            ("CHEQUE", "Chèque"),
                            ("MIXTE", "Paiement mixte"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant_recu", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monnaie_rendue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_vente", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("VALIDEE", "Validée"),
                            ("ANNULEE", "Annulée"),
                            ("REMBOURSEE", "Remboursée"),
                        ],
                        default="VALIDEE",
                        max_length=20,
                    ),
                ),
                ("points_fidelite_gagnes", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes",
                        to="gestioncaisse.caisse",
                    ),
                ),
                (
                    "caissier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes_effectuees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session_caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes",
                        to="gestioncaisse.sessioncaisse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                ("idligne", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remise_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "prix_apres_remise",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sous_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_vente",
                        to="gestionstock.produit",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="gestioncaisse.vente",
                    ),
                ),
            ],
        ),
    ]
